// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeUY6NnxA7oxuLoK5w6W9moDZIuvD3xmI',
    appId: '1:834974107954:web:54437cb0d59a68efe72f2b',
    messagingSenderId: '834974107954',
    projectId: 'legaspi-advwebprog-fireb',
    authDomain: 'legaspi-advwebprog-fireb.firebaseapp.com',
    storageBucket: 'legaspi-advwebprog-fireb.firebasestorage.app',
    measurementId: 'G-LMFYDQCKCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiV1LrpWB3XNGri57eCYXVL_Ohb-cg4kc',
    appId: '1:834974107954:android:84a8ebd9c9195184e72f2b',
    messagingSenderId: '834974107954',
    projectId: 'legaspi-advwebprog-fireb',
    storageBucket: 'legaspi-advwebprog-fireb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7xMNLwBsRfDw9Z_Zp5qPATpTOG3OW1GI',
    appId: '1:834974107954:ios:132b80a0b922838ce72f2b',
    messagingSenderId: '834974107954',
    projectId: 'legaspi-advwebprog-fireb',
    storageBucket: 'legaspi-advwebprog-fireb.firebasestorage.app',
    iosBundleId: 'com.example.legaspiAdvmobprog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeUY6NnxA7oxuLoK5w6W9moDZIuvD3xmI',
    appId: '1:834974107954:web:a31b4a6e3bfe7005e72f2b',
    messagingSenderId: '834974107954',
    projectId: 'legaspi-advwebprog-fireb',
    authDomain: 'legaspi-advwebprog-fireb.firebaseapp.com',
    storageBucket: 'legaspi-advwebprog-fireb.firebasestorage.app',
    measurementId: 'G-WWSSGB6EW1',
  );
}
